services:
  erpnext-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    networks:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8080:80"    # Nginx port for production
      - "8000:8000"  # Backend port
    environment:
      - FRAPPE_APP_PORT=8000
      - FRAPPE_APP_WORKERS=2
      - ENVIRONMENT=production
      - NODE_ENV=production
    env_file:
      - .env
    privileged: true  # Required for supervisor and nginx to run properly

networks:
  database:
    name: database
    external: true
