services:
  mariadb:
    image: mariadb:10.8
    restart: always
    networks:
      - database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - erpnext-mariadb:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
      - ./mariadb/my.cnf:/etc/my.cnf
      - ./mariadb/my.cnf:/etc/mysql/mariadb.conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always
    networks:
      - database
    ports:
      - "6379:6379"
    volumes:
      - erpnext-redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 10
    env_file:
      - .env

volumes:
  erpnext-mariadb:
  erpnext-redis:

networks:
  database:
    name: database
